steps:
  - name: pypyr.steps.echo
    in:
      echoMe: A
  - name: pypyr.steps.py
    in:
      py: raise ValueError('arb')
  - name: pypyr.steps.echo
    comment: 前のステップが常に失敗するため
             このステップは実行されない
    in:
      echoMe: unreachable

on_failure:
  - name: pypyr.steps.echo
    in:
      echoMe: B

